### ISSUE TITLE
scipy.spatial.Voronoi does not compute list of neighbouring points of each Voronoi cell

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/AutoLens#4]
scipy.spatial.Voronoi does not return a list giving the points that a voronoi vertex is adjacent with.  i.e., if a Voronoi cell had 5 neighbours, whos points corresponded to the entries [1, 6, 10, 25, 39] in an input list of points, the list [1, 6, 10, 25, 39] is not returned from the algorithm.

It can be calculated from the results of the algorithm using the ridge_points array, which gives a list of every neighbouring pair of points (i.e. if points 3 and 7 share a Voronoi vertex, and points 4 and 12 do, Voronoi.ridge_points will have entries of [3,7] and [4,12]). Making the desired array could be slow though, as one would need to apply a lot of filtering w/ logic. 

Alternatively, I think we can compute what we need using a Delaunay triangulation (scipy.spatial.Delaunay), which is probably pretty quick (given that Voronoi is so fast anyway). Still, its a shame to waste time and write code on something the voronoi algorithm should be able to compute.

The other option is we find another Voronoi algorithm.

**Comment by Jammy2211** [comment]
http://landlab.readthedocs.io/en/release/landlab.grid.voronoi.html#voronoi

This gives us areas too, which will be useful too :). Will get implementing next week!

**Comment by rhayes777** [comment]
So we have a list of pairs [[a, b], [a, c], [b, d],…]

We could take an array L of arrays with length N where N is the number of points.

Then, for each pair [A, B] we add the partner to each values array i.e. L[A].append(B) and L[B].append(A)

This only requires each element in the pairs array to be iterated through once, giving a time complexity of O(number of pairs) which is approximately O(C * N) where C is some constant or O(N) rendering it sufficiently efficient.

**Comment by Jammy2211** [comment]
Sounds sensible and a lot less effort. I'll push my analysis code with the Voronoi stuff up with some todo's for you to implement this.

**Comment by Jammy2211** [comment]
Implemented, was nice and simple.
