### ISSUE TITLE
List of neighbors of each Voronoi cell

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/AutoLens#7]
So, i was a bit stupid - this is a fairly trivial task. We have the list of neighbor pairs, e.g.:

pairs = [[0,1],[0,2],[1,4],[4,6]] etc.

We just have to go to each pair and put them in a neighbors vector i.e.:

for pair in pairs:
    neighbors[pair[0]] = pair[1]
    neighbors[pair[1]] = pair[0]

Im struggling to set up the list so it adds points... or do this as a numpy array. But its late, but if you know a quick code then let us know!

**Comment by rhayes777** [comment]
Maybe start with a list of lists that is the length of the number of pixels:

neighbours = [set() for _ in range(number_of_pixels)]

And then insert neighbours like this:

neighbours[pair[0]].add(pair[1])
neighbours[pair[1]].add(pair[0])

I’m not 100% on the syntax but I think that’s correct. I’m using a set just incase we get duplicated for some reason. Also it would be an efficient datatype for some later operations.

**Comment by Jammy2211** [comment]
Sets don't support indexing so probably not what we need? How would we get the neighbors of a specific source pixel?

**Comment by rhayes777** [comment]
Good point. It depends on how you want to use but yeah a list is probably better for that.

**Comment by Jammy2211** [comment]
Adapted to the code above - awesome thanks!
